version: 2.1
jobs:
  build_and_deploy:     
    docker:
        - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Install Sphinx
          command: |
            apt install -y python-pip && \
            python3 -m pip install -r requirements.txt
      - run:
          name: Make Docs
          command: |
            cd docs && make html
      - run: 
          name: Deploy Docs
          command: |
            echo $SA_KEY | gcloud auth activate-service-account --key-file=-
            gcloud config set project $PROJECT_ID
            gcloud config set compute/region $REGION
            gcloud app deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy